//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emsi.ServiceReference_emsams_ConEd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_emsams_ConEd.IConed")]
    public interface IConed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConed/GetSponsorInfo", ReplyAction="http://tempuri.org/IConed/GetSponsorInfoResponse")]
        string GetSponsorInfo(string statuses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConed/GetClassInfo", ReplyAction="http://tempuri.org/IConed/GetClassInfoResponse")]
        string GetClassInfo(string emptyRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConedChannel : emsi.ServiceReference_emsams_ConEd.IConed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConedClient : System.ServiceModel.ClientBase<emsi.ServiceReference_emsams_ConEd.IConed>, emsi.ServiceReference_emsams_ConEd.IConed {
        
        public ConedClient() {
        }
        
        public ConedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSponsorInfo(string statuses) {
            return base.Channel.GetSponsorInfo(statuses);
        }
        
        public string GetClassInfo(string emptyRequest) {
            return base.Channel.GetClassInfo(emptyRequest);
        }
    }
}
