//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace external_data_binding.emsams.ConEdSponsorInfo {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdSponsorInfo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdSponsorInfo", IsNullable=false)]
    public partial class Sponsors {
        
        private SponsorsSponsor[] sponsorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sponsor")]
        public SponsorsSponsor[] Sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdSponsorInfo")]
    public partial class SponsorsSponsor {
        
        private ushort sponsorIDField;
        
        private string emailField;
        
        private string nameField;
        
        private byte regionField;
        
        private bool regionFieldSpecified;
        
        private string sponsorNumberField;
        
        private string sponsorStatusDescriptionField;
        
        /// <remarks/>
        public ushort SponsorID {
            get {
                return this.sponsorIDField;
            }
            set {
                this.sponsorIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public byte Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegionSpecified {
            get {
                return this.regionFieldSpecified;
            }
            set {
                this.regionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SponsorNumber {
            get {
                return this.sponsorNumberField;
            }
            set {
                this.sponsorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorStatusDescription {
            get {
                return this.sponsorStatusDescriptionField;
            }
            set {
                this.sponsorStatusDescriptionField = value;
            }
        }
    }
}
