//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace external_data_binding.emsams.ConEdClassInfo {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo", IsNullable=false)]
    public partial class ClassInfo {
        
        private ClassInfoClass[] classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class")]
        public ClassInfoClass[] Class {
            get {
                return classField;
            }
            set {
                classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo")]
    public partial class ClassInfoClass {
        
        private uint classIDField;
        
        private ulong classNumberField;
        
        private bool classNumberFieldSpecified;
        
        private uint courseNumberField;
        
        private bool courseNumberFieldSpecified;
        
        private string courseTitleField;
        
        private string locationField;
        
        private string startDateTimeField;
        
        private string startTimeField;
        
        private string endDateTimeField;
        
        private string endTimeField;
        
        private byte approvedField;
        
        private ushort sponsorIDField;
        
        private string sponsorNumberField;
        
        private string sponsorNameField;
        
        private string publicContactEmailField;
        
        private decimal fR_MedTrauma_HrsField;
        
        private bool fR_MedTrauma_HrsFieldSpecified;
        
        private decimal fR_Other_HrsField;
        
        private bool fR_Other_HrsFieldSpecified;
        
        private decimal eMT_MedTrauma_HrsField;
        
        private bool eMT_MedTrauma_HrsFieldSpecified;
        
        private decimal eMT_Other_HrsField;
        
        private bool eMT_Other_HrsFieldSpecified;
        
        private decimal eMTP_MedTrauma_HrsField;
        
        private bool eMTP_MedTrauma_HrsFieldSpecified;
        
        private decimal eMTP_Other_HrsField;
        
        private bool eMTP_Other_HrsFieldSpecified;
        
        private decimal pHRN_MedTrauma_HrsField;
        
        private bool pHRN_MedTrauma_HrsFieldSpecified;
        
        private decimal pHRN_Other_HrsField;
        
        private bool pHRN_Other_HrsFieldSpecified;
        
        private string lengthField;
        
        private string emailField;
        
        private byte regionCouncilNumField;
        
        private byte classCountyCodeField;
        
        private string locationEmailField;
        
        /// <remarks/>
        public uint ClassID {
            get {
                return classIDField;
            }
            set {
                classIDField = value;
            }
        }
        
        /// <remarks/>
        public ulong ClassNumber {
            get {
                return classNumberField;
            }
            set {
                classNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassNumberSpecified {
            get {
                return classNumberFieldSpecified;
            }
            set {
                classNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint CourseNumber {
            get {
                return courseNumberField;
            }
            set {
                courseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseNumberSpecified {
            get {
                return courseNumberFieldSpecified;
            }
            set {
                courseNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CourseTitle {
            get {
                return courseTitleField;
            }
            set {
                courseTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return locationField;
            }
            set {
                locationField = value;
            }
        }
        
        /// <remarks/>
        public string StartDateTime {
            get {
                return startDateTimeField;
            }
            set {
                startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return startTimeField;
            }
            set {
                startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndDateTime {
            get {
                return endDateTimeField;
            }
            set {
                endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return endTimeField;
            }
            set {
                endTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte Approved {
            get {
                return approvedField;
            }
            set {
                approvedField = value;
            }
        }
        
        /// <remarks/>
        public ushort SponsorID {
            get {
                return sponsorIDField;
            }
            set {
                sponsorIDField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorNumber {
            get {
                return sponsorNumberField;
            }
            set {
                sponsorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorName {
            get {
                return sponsorNameField;
            }
            set {
                sponsorNameField = value;
            }
        }
        
        /// <remarks/>
        public string PublicContactEmail {
            get {
                return publicContactEmailField;
            }
            set {
                publicContactEmailField = value;
            }
        }
        
        /// <remarks/>
        public decimal FR_MedTrauma_Hrs {
            get {
                return fR_MedTrauma_HrsField;
            }
            set {
                fR_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FR_MedTrauma_HrsSpecified {
            get {
                return fR_MedTrauma_HrsFieldSpecified;
            }
            set {
                fR_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal FR_Other_Hrs {
            get {
                return fR_Other_HrsField;
            }
            set {
                fR_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FR_Other_HrsSpecified {
            get {
                return fR_Other_HrsFieldSpecified;
            }
            set {
                fR_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMT_MedTrauma_Hrs {
            get {
                return eMT_MedTrauma_HrsField;
            }
            set {
                eMT_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMT_MedTrauma_HrsSpecified {
            get {
                return eMT_MedTrauma_HrsFieldSpecified;
            }
            set {
                eMT_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMT_Other_Hrs {
            get {
                return eMT_Other_HrsField;
            }
            set {
                eMT_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMT_Other_HrsSpecified {
            get {
                return eMT_Other_HrsFieldSpecified;
            }
            set {
                eMT_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMTP_MedTrauma_Hrs {
            get {
                return eMTP_MedTrauma_HrsField;
            }
            set {
                eMTP_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMTP_MedTrauma_HrsSpecified {
            get {
                return eMTP_MedTrauma_HrsFieldSpecified;
            }
            set {
                eMTP_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMTP_Other_Hrs {
            get {
                return eMTP_Other_HrsField;
            }
            set {
                eMTP_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMTP_Other_HrsSpecified {
            get {
                return eMTP_Other_HrsFieldSpecified;
            }
            set {
                eMTP_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PHRN_MedTrauma_Hrs {
            get {
                return pHRN_MedTrauma_HrsField;
            }
            set {
                pHRN_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PHRN_MedTrauma_HrsSpecified {
            get {
                return pHRN_MedTrauma_HrsFieldSpecified;
            }
            set {
                pHRN_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PHRN_Other_Hrs {
            get {
                return pHRN_Other_HrsField;
            }
            set {
                pHRN_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PHRN_Other_HrsSpecified {
            get {
                return pHRN_Other_HrsFieldSpecified;
            }
            set {
                pHRN_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Length {
            get {
                return lengthField;
            }
            set {
                lengthField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return emailField;
            }
            set {
                emailField = value;
            }
        }
        
        /// <remarks/>
        public byte RegionCouncilNum {
            get {
                return regionCouncilNumField;
            }
            set {
                regionCouncilNumField = value;
            }
        }
        
        /// <remarks/>
        public byte ClassCountyCode {
            get {
                return classCountyCodeField;
            }
            set {
                classCountyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationEmail {
            get {
                return locationEmailField;
            }
            set {
                locationEmailField = value;
            }
        }
    }
}
