//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace external_data_binding.emsams.ConEdClassInfo {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo", IsNullable=false)]
    public partial class ClassInfo {
        
        private ClassInfoClass[] classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class")]
        public ClassInfoClass[] Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/ConEdClassInfo")]
    public partial class ClassInfoClass {
        
        private uint classIDField;
        
        private ulong classNumberField;
        
        private bool classNumberFieldSpecified;
        
        private uint courseNumberField;
        
        private bool courseNumberFieldSpecified;
        
        private string courseTitleField;
        
        private string locationField;
        
        private string startDateTimeField;
        
        private string startTimeField;
        
        private string endDateTimeField;
        
        private string endTimeField;
        
        private byte approvedField;
        
        private ushort sponsorIDField;
        
        private string sponsorNumberField;
        
        private string sponsorNameField;
        
        private string publicContactEmailField;
        
        private decimal fR_MedTrauma_HrsField;
        
        private bool fR_MedTrauma_HrsFieldSpecified;
        
        private decimal fR_Other_HrsField;
        
        private bool fR_Other_HrsFieldSpecified;
        
        private decimal eMT_MedTrauma_HrsField;
        
        private bool eMT_MedTrauma_HrsFieldSpecified;
        
        private decimal eMT_Other_HrsField;
        
        private bool eMT_Other_HrsFieldSpecified;
        
        private decimal eMTP_MedTrauma_HrsField;
        
        private bool eMTP_MedTrauma_HrsFieldSpecified;
        
        private decimal eMTP_Other_HrsField;
        
        private bool eMTP_Other_HrsFieldSpecified;
        
        private decimal pHRN_MedTrauma_HrsField;
        
        private bool pHRN_MedTrauma_HrsFieldSpecified;
        
        private decimal pHRN_Other_HrsField;
        
        private bool pHRN_Other_HrsFieldSpecified;
        
        private string lengthField;
        
        private string emailField;
        
        private byte regionCouncilNumField;
        
        private byte classCountyCodeField;
        
        private string locationEmailField;
        
        /// <remarks/>
        public uint ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public ulong ClassNumber {
            get {
                return this.classNumberField;
            }
            set {
                this.classNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassNumberSpecified {
            get {
                return this.classNumberFieldSpecified;
            }
            set {
                this.classNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint CourseNumber {
            get {
                return this.courseNumberField;
            }
            set {
                this.courseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseNumberSpecified {
            get {
                return this.courseNumberFieldSpecified;
            }
            set {
                this.courseNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CourseTitle {
            get {
                return this.courseTitleField;
            }
            set {
                this.courseTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte Approved {
            get {
                return this.approvedField;
            }
            set {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        public ushort SponsorID {
            get {
                return this.sponsorIDField;
            }
            set {
                this.sponsorIDField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorNumber {
            get {
                return this.sponsorNumberField;
            }
            set {
                this.sponsorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorName {
            get {
                return this.sponsorNameField;
            }
            set {
                this.sponsorNameField = value;
            }
        }
        
        /// <remarks/>
        public string PublicContactEmail {
            get {
                return this.publicContactEmailField;
            }
            set {
                this.publicContactEmailField = value;
            }
        }
        
        /// <remarks/>
        public decimal FR_MedTrauma_Hrs {
            get {
                return this.fR_MedTrauma_HrsField;
            }
            set {
                this.fR_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FR_MedTrauma_HrsSpecified {
            get {
                return this.fR_MedTrauma_HrsFieldSpecified;
            }
            set {
                this.fR_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal FR_Other_Hrs {
            get {
                return this.fR_Other_HrsField;
            }
            set {
                this.fR_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FR_Other_HrsSpecified {
            get {
                return this.fR_Other_HrsFieldSpecified;
            }
            set {
                this.fR_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMT_MedTrauma_Hrs {
            get {
                return this.eMT_MedTrauma_HrsField;
            }
            set {
                this.eMT_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMT_MedTrauma_HrsSpecified {
            get {
                return this.eMT_MedTrauma_HrsFieldSpecified;
            }
            set {
                this.eMT_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMT_Other_Hrs {
            get {
                return this.eMT_Other_HrsField;
            }
            set {
                this.eMT_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMT_Other_HrsSpecified {
            get {
                return this.eMT_Other_HrsFieldSpecified;
            }
            set {
                this.eMT_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMTP_MedTrauma_Hrs {
            get {
                return this.eMTP_MedTrauma_HrsField;
            }
            set {
                this.eMTP_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMTP_MedTrauma_HrsSpecified {
            get {
                return this.eMTP_MedTrauma_HrsFieldSpecified;
            }
            set {
                this.eMTP_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EMTP_Other_Hrs {
            get {
                return this.eMTP_Other_HrsField;
            }
            set {
                this.eMTP_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMTP_Other_HrsSpecified {
            get {
                return this.eMTP_Other_HrsFieldSpecified;
            }
            set {
                this.eMTP_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PHRN_MedTrauma_Hrs {
            get {
                return this.pHRN_MedTrauma_HrsField;
            }
            set {
                this.pHRN_MedTrauma_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PHRN_MedTrauma_HrsSpecified {
            get {
                return this.pHRN_MedTrauma_HrsFieldSpecified;
            }
            set {
                this.pHRN_MedTrauma_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PHRN_Other_Hrs {
            get {
                return this.pHRN_Other_HrsField;
            }
            set {
                this.pHRN_Other_HrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PHRN_Other_HrsSpecified {
            get {
                return this.pHRN_Other_HrsFieldSpecified;
            }
            set {
                this.pHRN_Other_HrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public byte RegionCouncilNum {
            get {
                return this.regionCouncilNumField;
            }
            set {
                this.regionCouncilNumField = value;
            }
        }
        
        /// <remarks/>
        public byte ClassCountyCode {
            get {
                return this.classCountyCodeField;
            }
            set {
                this.classCountyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationEmail {
            get {
                return this.locationEmailField;
            }
            set {
                this.locationEmailField = value;
            }
        }
    }
}
