//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace external_data_binding.emsams.PractitionerInfo {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerInfo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerInfo", IsNullable=false)]
    public partial class Practitioners {
        
        private PractitionersPractitioner[] practitionerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Practitioner")]
        public PractitionersPractitioner[] Practitioner {
            get {
                return this.practitionerField;
            }
            set {
                this.practitionerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerInfo")]
    public partial class PractitionersPractitioner {
        
        private string certificationNumberField;
        
        private string levelDescriptionField;
        
        private string countyNameField;
        
        private string regionalCouncilNameField;
        
        private string birthDateField;
        
        private string statusField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string miField;
        
        private string isInstructorField;
        
        /// <remarks/>
        public string CertificationNumber {
            get {
                return this.certificationNumberField;
            }
            set {
                this.certificationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LevelDescription {
            get {
                return this.levelDescriptionField;
            }
            set {
                this.levelDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionalCouncilName {
            get {
                return this.regionalCouncilNameField;
            }
            set {
                this.regionalCouncilNameField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MI {
            get {
                return this.miField;
            }
            set {
                this.miField = value;
            }
        }
        
        /// <remarks/>
        public string IsInstructor {
            get {
                return this.isInstructorField;
            }
            set {
                this.isInstructorField = value;
            }
        }
    }
}
