//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace external_data_binding.emsams.PractitionerStatusList {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerStatusList")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerStatusList", IsNullable=false)]
    public partial class PractitionerStatusList {
        
        private Status[] itemsField;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public Status[] Items {
            get {
                return itemsField;
            }
            set {
                itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return gUIDField;
            }
            set {
                gUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ems.health.state.pa.us/WcfWebServices/Schemas/PractitionerStatusList")]
    public enum Status {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        InActive,
        
        /// <remarks/>
        Revoked,
        
        /// <remarks/>
        Suspended,
        
        /// <remarks/>
        Dropped,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        Incomplete,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Do Not Certify and Expired")]
        DoNotCertifyandExpired,
        
        /// <remarks/>
        Probation,
        
        /// <remarks/>
        Denied,
        
        /// <remarks/>
        Deceased,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Deceased - LODD")]
        DeceasedLODD,
        
        /// <remarks/>
        SSA,
    }
}
